### ISSUE TITLE
Headphones Audio Lower - Not normal Volume for the Headphones - lower than 90%

### ISSUE THREAD

**Issue by ShibaSan-Bit** [LineageOS/android_device_xiaomi_davinci#2]
Hi, the audio for the headphones is not the normal, the rom volume for the headphones is in 85% of the total audio, i use all the Players Of Music but nothing change is the same issue.

LINEAGE OF PIG:

 
    <ctl name="RX_RX0 Digital Volume" value="84" />
    <ctl name="RX_RX1 Digital Volume" value="84" />
    <ctl name="RX_RX2 Digital Volume" value="84" />
    <ctl name="HPHL Volume" value="20" />
    <ctl name="HPHR Volume" value="20" />

    <ctl name="TX_DEC0 Volume" value="84" />
    <ctl name="TX_DEC1 Volume" value="84" />
    <ctl name="TX_DEC2 Volume" value="84" />
    <ctl name="TX_DEC3 Volume" value="84" />
    <ctl name="TX_DEC4 Volume" value="84" />
    <ctl name="TX_DEC5 Volume" value="84" />
    <ctl name="TX_DEC6 Volume" value="84" />
    <ctl name="TX_DEC7 Volume" value="84" />

    <ctl name="ADC1 Volume" value="8" />        -----------------   
    <ctl name="ADC2 Volume" value="8" />        -----------------     HERE IS THE ISSUE CHANGE THIS.
    <ctl name="ADC3 Volume" value="8" />        -----------------

NORMAL VOLUME FOR A ROM:

 
    <ctl name="WSA_RX0 Digital Volume" value="84" />
    <ctl name="WSA_RX1 Digital Volume" value="84" />
    <ctl name="RX_RX0 Digital Volume" value="84" />
    <ctl name="RX_RX1 Digital Volume" value="84" />
    <ctl name="RX_RX2 Digital Volume" value="84" />
    <ctl name="HPHL Volume" value="20" />
    <ctl name="HPHR Volume" value="20" />
    <ctl name="EAR SPKR PA Gain" value="G_DEFAULT" />

    <ctl name="TX_DEC0 Volume" value="84" />
    <ctl name="TX_DEC1 Volume" value="84" />
    <ctl name="TX_DEC2 Volume" value="84" />
    <ctl name="TX_DEC3 Volume" value="84" />
    <ctl name="TX_DEC4 Volume" value="84" />
    <ctl name="TX_DEC5 Volume" value="84" />
    <ctl name="TX_DEC6 Volume" value="84" />
    <ctl name="TX_DEC7 Volume" value="84" />

    <ctl name="ADC1 Volume" value="12" />             
    <ctl name="ADC2 Volume" value="12" />       <-------       HERE IS THE NORMAL VALUES
    <ctl name="ADC3 Volume" value="12" />

With this the audio is in the normal level...

Thanks <3

**Comment by essdev13** [comment]
@ShibaSan-Bit How have you build the image?
